# cat roles/requirements.yml
# Import directly from Galaxy
- src: geerlingguy.nginx
# Import from a local Git repository
- src: https://gitlab.com/jclaret/ansible-tower-shared-apache-role.git
  scm: git
  version: master
  name: shared-apache-role
